// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rolesDemoSSD.Data;

namespace rolesDemoSSD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220405175503_InitialCreate3")]
    partial class InitialCreate3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("rolesDemoSSD.Data.MyRegisteredUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("MyRegisteredUsers");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.IPN", b =>
                {
                    b.Property<string>("paymentID")
                        .HasColumnType("TEXT");

                    b.Property<string>("amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("cart")
                        .HasColumnType("TEXT");

                    b.Property<string>("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("custom")
                        .HasColumnType("TEXT");

                    b.Property<string>("intent")
                        .HasColumnType("TEXT");

                    b.Property<string>("payerCountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("payerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("payerFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("payerID")
                        .HasColumnType("TEXT");

                    b.Property<string>("payerLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("payerMiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("payerStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("paymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("paymentState")
                        .HasColumnType("TEXT");

                    b.HasKey("paymentID");

                    b.ToTable("IPNs");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InvoiceTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvoiceID");

                    b.HasIndex("UserID");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceID = 1,
                            InvoiceDate = new DateTime(2022, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceTotal = 7.99m,
                            PaymentMethod = "Visa",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("rolesDemoSSD.Models.MyUser", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserID");

                    b.ToTable("MyUser");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CartID = 0,
                            City = "Vancouver",
                            Country = "Canada",
                            Email = "joshig@bcit.ca",
                            FirstName = "Gaurav",
                            LastName = "Joshi",
                            Password = "P@ssw0rd!",
                            PhoneNumber = "7788888888",
                            PostalCode = "V5V43N",
                            StreetAddress = "45 Mayfair Ave",
                            UserName = "Gaurav453",
                            isAdmin = true
                        });
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Produce", b =>
                {
                    b.Property<int>("ProduceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("ProduceID");

                    b.ToTable("Produces");

                    b.HasData(
                        new
                        {
                            ProduceID = 1,
                            Description = "Oranges"
                        });
                });

            modelBuilder.Entity("rolesDemoSSD.Models.ProduceSupplier", b =>
                {
                    b.Property<int>("ProduceID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProduceID", "SupplierID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ProduceSuppliers");

                    b.HasData(
                        new
                        {
                            ProduceID = 1,
                            SupplierID = 1,
                            Qty = 25
                        });
                });

            modelBuilder.Entity("rolesDemoSSD.Models.ProductCart", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID", "CartID");

                    b.HasIndex("CartID");

                    b.ToTable("ProductCart");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.ProductVM", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("UserID");

                    b.ToTable("ProductVM");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Products", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("UserID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CartID = 0,
                            Category = "Climbing",
                            Description = "Black Diamond Hot Wire QucikPack 12cm",
                            InvoiceID = 1,
                            LocationTag = "/",
                            Photo = "black-diamond-hotforge-hybrid-quickdraw.jpg",
                            Price = 5.66m,
                            ProductName = "Black Diamond Hot Wire",
                            UserID = 1
                        },
                        new
                        {
                            ProductID = 2,
                            CartID = 0,
                            Category = "Baseball",
                            Description = "An Average Baseball Glove",
                            InvoiceID = 1,
                            LocationTag = "/",
                            Photo = "baseball-glove.jpeg",
                            Price = 10.66m,
                            ProductName = "Baseball Glove",
                            UserID = 1
                        },
                        new
                        {
                            ProductID = 3,
                            CartID = 0,
                            Category = "Winter",
                            Description = "Sick moves bro",
                            InvoiceID = 1,
                            LocationTag = "/",
                            Photo = "snowboard.jpg",
                            Price = 78.30m,
                            ProductName = "Snowboard",
                            UserID = 1
                        },
                        new
                        {
                            ProductID = 4,
                            CartID = 0,
                            Category = "Camping",
                            Description = "Great tent for sleeping outdoors",
                            InvoiceID = 1,
                            LocationTag = "/",
                            Photo = "coleman-tent.jpg",
                            Price = 63.29m,
                            ProductName = "Coleman Tent",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierName")
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierID = 1,
                            SupplierName = "Kin's Market"
                        },
                        new
                        {
                            SupplierID = 2,
                            SupplierName = "Fresh Street Market"
                        });
                });

            modelBuilder.Entity("rolesDemoSSD.ViewModels.RoleVM", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoleVM");
                });

            modelBuilder.Entity("rolesDemoSSD.ViewModels.UserRoleVM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("UserRoleVM");
                });

            modelBuilder.Entity("rolesDemoSSD.ViewModels.UserVM", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("UserVM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Cart", b =>
                {
                    b.HasOne("rolesDemoSSD.Models.MyUser", "MyUser")
                        .WithOne("Cart")
                        .HasForeignKey("rolesDemoSSD.Models.Cart", "CartID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MyUser");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Invoice", b =>
                {
                    b.HasOne("rolesDemoSSD.Models.MyUser", "MyUser")
                        .WithMany("Invoices")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MyUser");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.ProduceSupplier", b =>
                {
                    b.HasOne("rolesDemoSSD.Models.Produce", "Produce")
                        .WithMany("ProduceSuppliers")
                        .HasForeignKey("ProduceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("rolesDemoSSD.Models.Supplier", "Supplier")
                        .WithMany("ProduceSuppliers")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produce");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.ProductCart", b =>
                {
                    b.HasOne("rolesDemoSSD.Models.Cart", "Cart")
                        .WithMany("ProductCart")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("rolesDemoSSD.Models.Products", "Product")
                        .WithMany("ProductCart")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.ProductVM", b =>
                {
                    b.HasOne("rolesDemoSSD.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rolesDemoSSD.Models.MyUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Products", b =>
                {
                    b.HasOne("rolesDemoSSD.Models.Invoice", "Invoice")
                        .WithMany("Products")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("rolesDemoSSD.Models.MyUser", "MyUser")
                        .WithMany("Products")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("MyUser");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Cart", b =>
                {
                    b.Navigation("ProductCart");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Invoice", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.MyUser", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Invoices");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Produce", b =>
                {
                    b.Navigation("ProduceSuppliers");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Products", b =>
                {
                    b.Navigation("ProductCart");
                });

            modelBuilder.Entity("rolesDemoSSD.Models.Supplier", b =>
                {
                    b.Navigation("ProduceSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
